# Generated by Django 2.1.3 on 2018-11-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='designer_email',
            field=models.CharField(default='kiran@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
